### ISSUE TITLE
Linking with www does not work

### ISSUE THREAD

**Issue by daguar** [codeforamerica/redirect#33]
Just discovered this as a bug in our usage — for us:
- http://c4a.me/balance works
- www.c4a.me/balance gives a Heroku "no such app" error

This isn't a huge problem for us specifically since we can fix it, but my guess is some people are circulating www without realizing it doesn't work and will get silent errors.

**Comment by daguar** [comment]
cc @davidrleonard @lippytak

**Comment by davidrleonard** [comment]
Fixed, was a CNAME issue. 

On Heroku, adding the root domain to an app (i.e. domain.com) does not automatically grab traffic from the www (i.e. www.domain.com). My bad on not realizing that -- I've updated it, and www.c4a.me/balance should now work fine.

Thanks for the heads up.
